# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipstermonolithapp
services:
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  memcached:
    extends:
      file: ./memcached.yml
      service: memcached
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
  zookeeper:
    extends:
      file: ./kafka.yml
      service: zookeeper
